// monkey/compiler/compiler.go

package compiler

/*
	TODO: Understand why it is using objects and not the ast directly
*/

import (
	"monkey/ast"
	"monkey/code"
	"monkey/object"
)

type Compiler struct {
	instructions code.Instructions // Holds the generated bytecode
	constants []object.Object      // The constant pool
}

func NewCompiler() *Compiler {
	return &Compiler {
		instructions: code.Instructions {},
		constants: []object.Object {},
	}
}

func (this *Compiler) Compile(program ast.Node) error {
	return nil
}

// 1. Holds the result of compiling the Program AST into instructions
// 2. Is the final product of the compilation meant to be used for the VM to
// execute the program
type Bytecode struct {
	Instructions code.Instructions
	Constants []object.Object
}

func (this *Compiler) NewBytecode() *Bytecode {
	return &Bytecode {
		Instructions: this.instructions,
		Constants: this.constants,
	}
}
